server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名
  client:
    register-with-eureka: false #表示是否向eureka注册自己
    fetch-registry: false #为false表示自己为注册中心
    service-url: #监控中心
      defaultZone: http://eureka7000.com:7000/eureka,http://eureka7002.com:7002/eureka